### ISSUE TITLE
Why Drone and Private Registry?

### ISSUE THREAD

**Issue by jhollowe** [ArchiveTeam/grab-base-df#1]
I was wondering why this (and most of the AT containers) are using Drone for builds rather than something more standard like GitHub Actions? Within the past few month a lot of development has happen (which I'm super excited for) but it looks like that development has included some concerning moves from open and visible systems to private systems.

I'm also concerned about the repository used for these images. It appears to be a personal registry which is very opaque to trying to get more information about images. When attempting to browser to atdr.meo.ws in a browser, all that is returned is "nope" which is neither helpful or gives any visibility or traceability of the images and tags stored there. There are numerous public registries that have a solid reputation that offer free storage and bandwidth for opensource/public images like this (GitHub Container Registry would integrate well with GH Actions). These registries also show information on the images and available tags.

It seems like multiple AT repos have recently switched to using these private tools which is concerning, especially for a tool that is designed to run various other projects and code. While containerization does give some isolation and security, it is not a panacea for concerns. A `docker pull` is still just pulling code from the internet and running it. While not as bad as a `curl | bash`, it still requires trust in the source of the image. A registry that gives no information on its contents and is hosted on some unknown personal machine is not a registry that can be easily trusted.

The removal of "trusted build" [here](https://github.com/ArchiveTeam/warrior-dockerfile/commit/c776abd3438169f20d011538e3ef5e434f6cec8a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R9) is also interesting but not specifically malicious.

**Comment by km09** [comment]
> I was wondering why (...) Drone for builds rather than something more standard like GitHub Actions?

Drone was 'easier' to some extent. We needed it anyway for various other parts of our infra, so keeping all CI in one place made sense. We did also push things to Dockerhub under [another account](https://hub.docker.com/u/warcforceone) for a while, though stopped using that when we moved everything to drone. This was mainly due to the new dockerhub limits, but also allowed us to bring CI 'in-house' and not rely on GitHub for everything. We run Gitea elsewhere for too, for similar reasons.


> I'm also concerned about the repository used for these images

Your concerns here are somewhat valid. Yes, it's under a personal domain. No, we're not doing anything nasty. Again, it was easier at the time and will probably be moved (at some point) to a different domain that makes things clearer.

> There are numerous public registries that have a solid reputation

So did DockerHub, but now look at it.

Admittedly - there's no reason why we _can't_ just push to multiple registries, but what difference does it make? You shouldn't inherently trust something because it's on GitHub vs any other domain out there, it'd be the exact same image. The dockerfiles are available in each repo and anyone can build locally if that's a concern.


> It seems like multiple AT repos have recently switched to using these private tools which is concerning

Yes, we run some services in-house rather than risk being burned by third party services. We're not making anything 'private', we're just not pushing to Dockerhub as standard. Maybe I misunderstood your point here, can you elaborate?


> A registry that gives no information on its contents and is hosted on some unknown personal machine is not a registry that can be easily trusted.

The people running the registry are the same people putting the code in these repos. There is a level of trust there, but if you don't trust the images you should likely not trust the repos at all. Nobody is forced to use the registry for docker images. It's provided for ease of use for those that want a set-and-forget option. Also worth clarifying it's not a 'personal machine', there's plenty of people with access and it's one of our core services.


> The removal of "trusted build" [here](https://github.com/ArchiveTeam/warrior-dockerfile/commit/c776abd3438169f20d011538e3ef5e434f6cec8a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R9) is also interesting but not specifically malicious.

I'm glad you find this to be _not specifically malicious_. There's not really much to say here. I updated the readme, and altered some text while I was at it.

**Comment by jhollowe** [comment]
Thanks for the clarifications!

Part of my thinking for questioning the use of Drone is that it makes it harder to try to contribute to the CI process since the results of the builds are not visible to people not it the team. Obviously, I can do a `docker build` of a clone of the repo for testing the code/Dockerfile for anything I would like to contribute. However, if I would like to contribute to the CI/CD process, I can't see if a config file is broken in syntax or content when Drone goes to execute. I completely understand and support consolidating on a single CI toolchain though. If some visibility into the build logs were available, it would help solve this issue.

My main concern/issue with a private/non-standard registry is the lack of visibility into the available images and tags. If I want to see what tags are available for a certain image, on other registries I can view a list of the tags. With the currently use registry, there is no functionality for this. For this image this is probably not a big issue since this will mostly be used by other images, but for "end user" images, this limits what users can see about the images they would like to use. If the registry could show this information, it would greatly increase the usability of the images it contains and allow for stable updates by targeting specific versions (rather than just trusting that using `:latest` will be stable).

Pushing to multiple registries isn't a must, but it would help reduce traffic requirements for the main registry and would allow some workflows to have faster access to the images (e.g. having the images in GHCR would (theoretically) allow faster pulls for things running in Actions).

**Comment by km09** [comment]
> Part of my thinking for questioning the use of Drone is that it makes it harder to try to contribute to the CI process since the results of the builds are not visible to people not it the team.

This is understandable - though really being that all we're doing is building docker images here there's not a whole lot in the CI process. For some repositories you'll fine a [.drone.yml](https://github.com/ArchiveTeam/wget-lua/blob/v1.20.3-at/.drone.yml) file that outlines what drone will be doing. To save us the headache of putting that in each repo, by default it's purely a case of docker build -> push to the repository (though admittedly this could maybe be documented somewhere like the wiki)

>  If the registry could show this information, it would greatly increase the usability of the images

Our use case here for projects always relies on people using :latest unless advised otherwise. We set minimum versions per project at the tracker level, and if you're not running latest you're liable to suddenly find your worker doing nothing at all. There should be no other tags used, which really negates the need to see a list of available builds. We really try and push a baseline of 'use the docker images and watchtower for automatic updates' because having people manually restart their workers for each update is cumbersome and always a slow process. Using watchtower, we can have this completed within a matter of minutes.
As always, there are exceptions to the rule. wget-lua for example has an openssl version and a gnutls version, but those are only ever referenced by other images and not used directly.

**Comment by jhollowe** [comment]
I totally understand both points. The use case for this repo is very single-purpose.

My main reason for discussing contributing to the Drone config is that I'd like to help get wget-lua, grab-base, and warrior-dockerfile all doing multiarch builds for at least amd64 and arm64. From my (cursory) look at the Drone documentation, it looks like changes/additions to the drone file would be required. To properly do this would need access to the output of Drone to make sure everything was working.

> Our use case here for projects always relies on people using :latest unless advised otherwise.

I totally get this with all the dependency images and constant updates.
